name: Build Dependabot Bundler PR

# read-only repo token
# no access to secrets
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ./dependabot-pr
      - name: Cache dependabot pull request changes
        uses: actions/cache@v2
        with:
          path: ./dependabot-pr
          key: dependabot-pr-${{ github.run_id }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@fdcfbcf14ec9672f6f615cb9589a1bc5dd69d262
        with:
          ruby-version: 2.7
      - name: Bundle
        run: |
          bundle install
      - name: Save branch ref
        run: |
          echo ${{ github.ref }} > ./dependabot-pr/BRANCH_REF
      - run: licensed cache
      - run: git status
      - name: Copy changed licenses
        run: |
          git status --porcelain v1 . | grep '.licenses/' | awk {'print $2'} | xargs -I {} cp --parents {} ./dependabot-pr
