# This workflow runs after `Build Dependabot Bundler PR` completes with a
# READ-WRITE GITHUB_TOKEN from the default branch and pushes updated license
# file changes back to the Dependabot PR branch.

# We run this as a separate workflow to isolate potentially unsafe `bundle
# install`s.

name: Update Dependabot Bundler PR
on:
  workflow_run:
    workflows: ["Build Dependabot Bundler PR"]
    types:
      - completed

jobs:
  update:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download pr changes
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "dependabot-pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('/home/runner/work/dependabot-pr.zip', Buffer.from(download.data));
      - run: mkdir -p /home/runner/work/dependabot-pr
      - name: Unpack pr changes
        run: unzip -o /home/runner/work/dependabot-pr.zip -d /home/runner/work/
      - run: ls -la ${{github.workspace}}
      - run: ls -la /home/runner/work/dependabot-pr
      - name: Set branch name
        run: echo "BRANCH_NAME=$(cat '/home/runner/work/dependabot-pr/BRANCH_REF' | sed 's/refs\/heads\///')" >> $GITHUB_ENV
      - name: Checkout the branch from 'Build Dependabot Bundler PR'
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
      - run: yes | cp -af /home/runner/work/dependabot-pr/. .
      - run: git status
      - name: Configure git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      # NOTE: Prefixing commit messages with `[dependabit skip]` allows
      # dependabot to rebase/update the pull request, force-pushing over any
      # changes
      - name: Commit license changes
        run: |
          if [[ $(git status | grep '.licenses/') ]]; then
            git add .licenses/
            git commit -m "[dependabot skip] Update licenses"
          else
            echo "Licenses were not changed"
          fi
      - name: Push changes back to dependabot/bundler branch
        run: |
          if [[ "$BRANCH_NAME" =~ ^dependabot/bundler* ]]; then
            git push origin $BRANCH_NAME
          else
            echo "Branch ref doesn't look like a dependabot/bundler branch: $BRANCH_REF"
            exit 1
          fi
