name: Update Dependabot Bundler PR

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Build Dependabot Bundler PR"]
    types:
      - completed

jobs:
  update:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependabot pull request changes
        uses: actions/cache@v2
        with:
          path: ./dependabot-pr
          key: dependabot-pr-${{github.event.workflow_run.id }}
      - name: Unpack pull request changes
        run: yes | cp -af ./dependabot-pr/. .
      - name: Set branch name
        run: echo "BRANCH_NAME=$(cat './BRANCH_REF' | sed 's/refs\/heads\///')" >> $GITHUB_ENV
      - name: Configure git
        run: |
          git config --local user.email "email"
          git config --local user.name "actions[bot]"
      - name: Checkout the branch from 'Build Dependabot Bundler PR'
        run: git checkout --progress --force -B $BRANCH_NAME refs/remotes/origin/$BRANCH_NAME
      - run: git status
      - name: Commit Gemfile_next.lock and licenses
        run: |
          if [[ $(git status | grep '.licenses/') ]]; then
            git add .licenses/
            git commit -m "[dependabot skip] Update licenses"
          else
            echo "Licenses were not changed"
          fi
      - name: Push changes back to branch
        run: |
          if [[ "$BRANCH_NAME" =~ ^mai* ]]; then
            git push origin $BRANCH_NAME
          else
            echo "Branch ref doesn't look like a dependabot/bundler branch: $BRANCH_REF"
            exit 1
          fi
